In [67]:
import numpy as np
import matplotlib.pyplot as plt

### 1. Two fair coin flips produce exactly two heads

In [14]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250077

In [18]:
tests.sum(axis=0)

array([499816, 499587])

In [24]:
(tests.sum(axis=1) == 0)


array([ True, False, False, ...,  True, False,  True])

### 2. Three fair coin flips produce exactly one head

In [32]:
coin_3_tests = np.random.randint(2, size=(int(1e6), 3))
coin_3_tests

array([[0, 1, 1],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 0]])

In [38]:
(coin_3_tests.sum(axis=1) == 1).mean()

0.374768

### 3. Three bias coin flips with P(H) = 0.6 produce exactly one head

In [41]:
coin_3_bias_tests = np.random.choice([0,1],size=(int(1e6),3), p=[0.6, 0.4])
coin_3_bias_tests

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [42]:
(coin_3_bias_tests.sum(axis=1) == 2).mean()

0.2876

### 4. A dice rolls an even number

In [47]:
dice_tests = np.random.randint(6,size=(int(1e6)))
dice_tests

array([3, 1, 4, ..., 0, 5, 5])

In [48]:
(dice_tests %2 == 0).mean()

0.499957

### 5. Two dice roll a double

In [61]:
dice_2_tests= np.random.choice(range(1,7), size=(int(1e6)))
dice_2_tests_2 = np.random.choice(range(1,7), size=(int(1e6)))
(dice_2_tests == dice_2_tests_2).mean()

0.1669

## Binomial Distributions

### 1. A fair coin flip produces heads

In [107]:
np.random.binomial(1, 0.5, size=(int(1e6))).mean()

0.50065

### 2. Five fair coin flips produce exactly one head

In [110]:
(np.random.binomial(5, 0.5, size=(int(1e6))) == 1).mean()

0.156082

### 3. Ten fair coin flips produce exactly four heads

In [111]:
(np.random.binomial(10, 0.5, size=(int(1e6))) == 4).mean()

0.204413

### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

In [114]:
(np.random.binomial(5, 0.8, size=(int(1e6))) == 5).mean()

0.32777

### 5. Ten biased coin flips with P(H) = 0.15 produce at least three heads

In [116]:
(np.random.binomial(10, 0.15, size=(int(1e6))) >= 3).mean()

0.179828